In [1]:
import pandas as pd

In [2]:
model_list = ('Cell2fateDynamicalModel_400epochs', 'Cell2fateDynamicalModel_750epochs',
             'Cell2fateDynamicalModel', 'Cell2fateDynamicalModel_batchSize10000epochs1000',
              'Cell2fateDynamicalModel_batchSize128', 'Cell2fateDynamicalModel_batchSize128epochs250',
             'Cell2fateDynamicalModel_batchSize128epochs250', 'Cell2fateDynamicalModel_lr0005epochs1000')

In [3]:
res_list = []
for i in range(len(model_list)):
    res= pd.read_csv('/nfs/team283/aa16/data/fate_benchmarking/benchmarking_results/' +
                model_list[i]
                + '__CBDC_fullBenchmark.csv', index_col=0)
    res_list += [res]
    tab = pd.concat(res_list, axis = 1)
tab.columns = [m[22:] for m in model_list]
tab

,l_400epochs,l_750epochs,l,l_batchSize10000epochs1000,l_batchSize128,l_batchSize128epochs250,l_batchSize128epochs250,l_lr0005epochs1000
0-0-0,0.586732,0.538693,0.594075,-0.001837,0.514182,0.580447,0.580447,0.573679
0-0-1,0.359557,0.191583,0.463913,-0.005595,0.098436,0.309579,0.309579,0.322158
0-0-2,-0.712021,0.618993,0.394765,-0.000838,0.693577,-0.655329,-0.655329,0.595474
0-0-3,-0.735798,0.566093,-0.656466,0.087196,0.595644,NaN,NaN,0.287732
0-0-4,0.111207,-0.114400,0.381200,0.081059,-0.005388,NaN,NaN,-0.467861
0-1-0,-0.408628,-0.399245,-0.458042,-0.028599,-0.502503,NaN,NaN,-0.557840
0-1-1,0.218145,0.489980,0.386086,0.079796,0.535529,NaN,NaN,0.354001
0-1-2,0.481294,-0.653426,0.720890,0.267805,-0.667502,NaN,NaN,0.623873
0-1-3,0.627341,-0.789516,-0.678799,-0.207908,NaN,NaN,NaN,0.570331
0-1-4,-0.479306,-0.455606,-0.045420,-0.226429,NaN,NaN,NaN,-0.428066
1-0-0,0.365940,-0.508254,0.050488,0.233614,NaN,NaN,NaN,-0.090828
1-0-1,0.276947,0.102505,0.164327,0.044422,NaN,NaN,NaN,0.212862
1-0-2,0.683047,-0.681591,0.553600,0.103574,NaN,NaN,NaN,0.569862
1-0-3,-0.507948,0.529878,0.511646,-0.337909,NaN,NaN,NaN,0.580029
1-0-4,-0.461924,0.264670,-0.261956,-0.151369,NaN,NaN,NaN,-0.326936
1-1-0,-0.523098,-0.548956,-0.114207,-0.256804,NaN,NaN,NaN,-0.533516
1-1-1,0.332432,-0.061127,0.340066,0.080706,NaN,NaN,NaN,0.173140
1-1-2,NaN,-0.659558,0.644151,0.354715,NaN,NaN,NaN,0.633730
1-1-3,NaN,0.618394,-0.258631,-0.025840,NaN,NaN,NaN,0.627773
1-1-4,NaN,-0.505592,0.300465,-0.012191,NaN,NaN,NaN,-0.411044
AVERAGE,NaN,-0.072824,0.151607,0.003878,NaN,NaN,NaN,0.165428